module.exports={
    css:{
        loaderOptions:{
            scss:{
                additionalData:`
                @import"./resources/ssss/foundation/_f-variables.scss";
                `
            }
        }
    },
}